### ISSUE TITLE
[BUG] Game crash on 1.20.4 with PackItUp! mod

### ISSUE THREAD

**Issue by chefexperte** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#115]
**Describe the bug**
When opening the world creation the game crashes, because of some weird error/incompatibility with PackItUp! mod. I don't  know which GitHub issues page to post this on, but I'll start here. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the game
2. Click on New World
3. Crash

**Expected behaviour**
The world creation screen should open

**Minecraft Version**
1.20.4

**CTOV Version**
3.4.2

**Add-ons used**
No addons, but other mods. Mod list is in the crash report

**Log**

<details> 
  <summary>Crash log </summary>

```
[00:09:23] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class fzzyhmstrs.pack_it_up.recipe.PackBenchRecipeSerializer does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.Codec method_53736()' of interface net.minecraft.class_1865.
	at java.util.function.Function.lambda$andThen$1(Function.java:88) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:57) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_31130(class_525.java:331) ~[client-intermediary.jar:?]
	at net.minecraft.class_526.method_19944(class_526.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 17 more
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-03-19 00:09:23
Description: mouseClicked event handler

java.lang.AbstractMethodError: Receiver class fzzyhmstrs.pack_it_up.recipe.PackBenchRecipeSerializer does not define or inherit an implementation of the resolved method 'abstract com.mojang.serialization.Codec method_53736()' of interface net.minecraft.class_1865.
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:57)
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56)
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at net.minecraft.class_1863.method_17720(class_1863.java:131)
	at net.minecraft.class_1863.method_20705(class_1863.java:56)
	at net.minecraft.class_1863.method_18788(class_1863.java:35)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.class_525.method_31130(class_525.java:331)
	at net.minecraft.class_526.method_19944(class_526.java:54)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$4(KeyDispatchCodec.java:57)
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56)
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$1(MapDecoder.java:52)
	at com.mojang.serialization.DataResult.lambda$flatMap$11(DataResult.java:139)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:137)
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at net.minecraft.class_1863.method_17720(class_1863.java:131)
	at net.minecraft.class_1863.method_20705(class_1863.java:56)
	at net.minecraft.class_1863.method_18788(class_1863.java:35)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.class_525.method_31130(class_525.java:331)
	at net.minecraft.class_526.method_19944(class_526.java:54)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_526
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
	at net.minecraft.class_310.method_1523(class_310.java:1352)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 12.311s
	Wall uptime: 7.425s
	High-res time: 6.883s
	Client ticks: 116 ticks / 5.800s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Default-Dark-Mode-1.20.2+-2023.11.0.zip, file/UniqueDarkRefined 1.20.4 (free).zip

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.7.7-200.fc39.x86_64
	Java Version: 17.0.9, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	<redacted>
	Fabric Mods: 
		ctov: ChoiceTheorem's Overhauled Village 3.4.2
		fabric-api: Fabric API 0.92.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.82+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.18+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.3+875cc1474f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.16+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.14+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.51+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		pack_it_up: Pack It Up! 0.3.1+1.20.1
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 550.54.14, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 6/6 chunks
	Resource Packs: vanilla, fabric, file/Default-Dark-Mode-1.20.2+-2023.11.0.zip, file/UniqueDarkRefined 1.20.4 (free).zip
	Current Language: en_gb
	Locale: en_GB
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/aaron/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Distant Horizons/.minecraft/crash-reports/crash-2024-03-19_00.09.23-client.txt
Process exited with code 255.
```

</details>

**Additional context**
This is the PackItUp version I have:  
https://modrinth.com/mod/pack-it-up/version/0.3.1+1.20.1

**Comment by ChoiceTheorem** [comment]
Not related to CTOV
