### ISSUE TITLE
[BUG] Couldnt parse element "loot_tables:ctov:chests/village/village_forager"

### ISSUE THREAD

**Issue by Invidious** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#116]
**Describe the bug**
Im not sure exactly what effects it has on the mod but it appears in the server log upon start up

**To Reproduce**
Steps to reproduce the behaviour:
1. Start server with mod in mods folder

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.2

**Add-ons used**
N/A

**Log**
`[13:55:19] [Worker-Main-3/ERROR]: Couldn't parse element loot_tables:ctov:chests/village/village_forager
com.google.gson.JsonSyntaxException: Missing expand, expected to find a Boolean
at net.minecraft.class_3518.method_15270(class_3518.java:181) ~[server-intermediary.jar:?]
at net.minecraft.class_91$class_92.method_450(class_91.java:86) ~[server-intermediary.jar:?]
at net.minecraft.class_91$class_92.method_443(class_91.java:72) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_441(class_85.java:151) ~[server-intermediary.jar:?]
at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[server-intermediary.jar:?]
at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[server-intermediary.jar:?]
at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:102) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15272(class_3518.java:471) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.method_358(class_55.java:173) ~[server-intermediary.jar:?]
at net.minecraft.class_55$class_57.deserialize(class_55.java:169) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar:?]
at net.minecraft.class_3518.method_15291(class_3518.java:463) ~[server-intermediary.jar:?]
at net.minecraft.class_3518.method_15283(class_3518.java:481) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.method_340(class_52.java:250) ~[server-intermediary.jar:?]
at net.minecraft.class_52$class_54.deserialize(class_52.java:246) ~[server-intermediary.jar:?]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
at net.minecraft.class_8490.method_51205(class_8490.java:64) ~[server-intermediary.jar:?]
at net.minecraft.class_8490.method_51204(class_8490.java:48) ~[server-intermediary.jar:?]
at net.minecraft.class_60.method_51195(class_60.java:55) ~[server-intermediary.jar:?]
at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
at net.minecraft.class_60.method_51189(class_60.java:55) ~[server-intermediary.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491) ~[?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073) ~[?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035) ~[?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187) ~[?:?]`

**Comment by ChoiceTheorem** [comment]
It does nothing. Except you install byg then it'll disappear!
