### ISSUE TITLE
[CRASH] Failed to get element ResourceKey[minecraft:worldgen/processor_list / ctov:detailing/plains/roads]

### ISSUE THREAD

**Issue by burdoto** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#165]
**Describe the bug**
A specific user was unable to log in, as loading chunks around them caused this error repeatedly and ultimately crashing server.

**To Reproduce**
Steps to reproduce the behaviour:
(unknown)

**Expected behaviour**
no crash

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.4

**Do you install Lithostitched?(1.20+)**
Version 1.20.1-1.1.5

**Log**
```
[25Jun2024 02:15:54.746] [Server thread/ERROR] [net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece/]: Failed to get element ResourceKey[minecraft:worldgen/processor_list / ctov:detailing/plains/roads]
[25Jun2024 02:15:54.746] [Server thread/ERROR] [net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer/]: Exception loading structure piece with id minecraft:jigsaw
java.lang.IllegalStateException: Invalid pool element found
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_163129_(PoolElementStructurePiece.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:PoolElementStructurePieceMixin,pl:mixin:A}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.<init>(PoolElementStructurePiece.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:PoolElementStructurePieceMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pieces.PiecesContainer.m_192753_(PiecesContainer.java:73) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_226857_(StructureStart.java:57) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:conquered,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:conquered}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188254_(ChunkSerializerMixin.java:454) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.storage.ChunkSerializerMixin,pl:mixin:APP:railways-common.mixins.json:ChunkSerializerMixin,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_188230_(ChunkSerializerMixin.java:199) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.level.chunk.storage.ChunkSerializerMixin,pl:mixin:APP:railways-common.mixins.json:ChunkSerializerMixin,pl:mixin:APP:architectury.mixins.json:MixinChunkSerializer,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.m_288112_(ChunkMapMixin.java:578) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.level.ChunkMapMixin,pl:mixin:APP:railways.mixins.json:ChunkMapAccessor,pl:mixin:APP:ae2.mixins.json:chunkloading.ChunkMapMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ChunkMapMixin_Optimize,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:trackingrange.ChunkManagerMixin_TrackingRange,pl:mixin:APP:securitycraft.mixins.json:camera.ChunkMapMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ChunkMapMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache_MainThreadExecutorMixin.java:541) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCache_MainThreadExecutorMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache_MainThreadExecutorMixin.java:635) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCache_MainThreadExecutorMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCacheMixin.java:131) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:mixins.arclight.core.json:server.level.ServerChunkCacheMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_6522_(LevelMixin.java:187) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
	at net.minecraft.world.level.LevelReader.m_46819_(LevelReader.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:computing_frames,re:mixin,re:classloading,re:mixin}
	at net.minecraft.world.level.Level.m_6325_(LevelMixin.java:182) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
	at net.minecraft.world.level.Level.m_8055_(LevelMixin.java:355) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.arclight.core.json:world.level.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LevelAccessor,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud}
	at net.minecraft.world.level.SignalGetter.m_277185_(SignalGetter.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:computing_frames,re:mixin,re:classloading,re:mixin}
	at net.minecraft.world.level.SignalGetter.m_276867_(SignalGetter.java:72) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:computing_frames,re:mixin,re:classloading,re:mixin}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:171) ~[refinedstorage-1.12.4.jar%23423!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.12.4.jar%23423!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.12.4.jar%23423!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2386!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactoryMixin.java:930) ~[forge-1.20.1-47.2.20-universal.jar%23468!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:899) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:APP:lithostitched.mixins.json:server.DedicatedServerMixin,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2071) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23463!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.letmedespawn.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin,re:mixin}
```
Note that while refinedstorage appears in this iteration of the message; it does not seem to be related as there's a couple of different mods involved.
This message is printed like ~29 times with various detail stacktraces before the server ultimately gives up and crashes.

Removing CTOV temporarily solved the problem.

**Comment by ChoiceTheorem** [comment]
Did you update recently?

**Comment by burdoto** [comment]
yes, we did update this modpack recently, like one or two weeks ago

**Comment by burdoto** [comment]
we did not intentionally add any addons, and wouldn't know where to put them either

**Comment by ChoiceTheorem** [comment]
I'd like some more info:
1. Did the crash is exclusive to that player?
2. Did the player install CTOV on the client side?
3. Did you update CTOV from 3.4.3 to 3.4.4?

**Comment by burdoto** [comment]
- we dont know; so far we have been going without the mod and we're not sure on how to reproduce this issue
- yes, they did; since this is in the context of an official modpack server
- we did not try other CTOV versions at the time, because the versions 3.4.4 and 3.4.5 were not available at that point in time

**Comment by ChoiceTheorem** [comment]
1. CTOV is exclusively serverside mod. I don't know why they'd install it on client side.

**Comment by burdoto** [comment]
we had it included in our modpack for singleplayer users to also enjoy the content

**Comment by burdoto** [comment]
sorry, but why exactly did you close this? have you been unable to reproduce?
this is an issue keeping us from including this mod in our packs ..
