### ISSUE TITLE
[BUG] Failure to load the mod in 1.20.x

### ISSUE THREAD

**Issue by watermelon0guy** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#185]
**Describe the bug**
Failed to load with NeoForge

**To Reproduce**
Load with NeoForge

**Expected behaviour**
Game launches

**Minecraft Version**
NeoForge 1.20.1 47.1.106
**CTOV Version**
3.4.7 NeoForge

**Do you install Lithostitched?(1.20+)**
Yes
**Log**
[latest.log](https://github.com/user-attachments/files/16480856/latest.log)

**Comment by ChoiceTheorem** [comment]
That's a small error will fix it soon.

**Comment by ChoiceTheorem** [comment]
After a small work up, I think you should try installing neofroge first.

**Comment by pokesmells** [comment]
> After a small work up, I think you should try installing neoforge first.

The same happens on Fabric:

`Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config ctov-common.mixins.json for mod ctov
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config ctov-common.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'ctov-common.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1395)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
	... 7 more
`

**Comment by ChoiceTheorem** [comment]
I recently migrate by IDE. I accidentally compile the mod with Java 21 instead of 17 for 1.20.x

**Comment by ChoiceTheorem** [comment]
Until further notice, I'll remove the version from circulation for now.

**Comment by ChoiceTheorem** [comment]
A new CTOV 3.4.7 is out should solve the problem!
