### ISSUE TITLE
Couldn't load tag ctov:wares/cardboard_box

### ISSUE THREAD

**Issue by tarkh** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#192]
**Describe the bug**
Each boot getting same error in logs from CTOV

**To Reproduce**
Install Forge 47.3.5, Minecraft 1.20.1
Install mods:
```
[Forge]CTOV-v3.4.5.jar
lithostitched-forge-1.20.1-1.1.8.jar
```

**Expected behaviour**
No errors from CTOV

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.5

**Do you install Lithostitched?(1.20+)**
Yes

**Log**
```
[INFO] Emulated terminal mode is active. You can directly input content in the terminal and use Ctrl, Tab, and other function keys.
WARNING: Using incubator modules: jdk.incubator.vector
[17:14:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.3.5, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[17:14:40] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.3 by N/A; OS Linux arch amd64 version 6.9.2-arch1-1
[17:14:40] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[17:14:40] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[17:14:40] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraftforge/fmlcore/1.20.1-47.3.5/fmlcore-1.20.1-47.3.5.jar is missing mods.toml file
[17:14:40] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.3.5/javafmllanguage-1.20.1-47.3.5.jar is missing mods.toml file
[17:14:40] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.3.5/lowcodelanguage-1.20.1-47.3.5.jar is missing mods.toml file
[17:14:40] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraftforge/mclanguage/1.20.1-47.3.5/mclanguage-1.20.1-47.3.5.jar is missing mods.toml file
[17:14:40] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[17:14:41] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:14:41] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[17:14:47] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.3.5, for MC 1.20.1 with MCP 20230612.114412
[17:14:47] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.3.5 Initialized
[17:14:48] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[17:14:48] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 47.3.5 Target: null
[17:14:48] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [ctov] Starting version check at https://api.modrinth.com/updates/fgmhI8kH/forge_updates.json
[17:14:48] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [ctov] Found status: UP_TO_DATE Current: 3.4.5 Target: null
[17:14:48] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:14:49] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraft/server/1.20.1-20230612.114412/server-1.20.1-20230612.114412-srg.jar%23105!/assets/.mcassetsroot' uses unexpected schema
[17:14:49] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/opt/mcsmanager/daemon/data/InstanceData/f068f943654646e5859691d8b71b8762/libraries/net/minecraft/server/1.20.1-20230612.114412/server-1.20.1-20230612.114412-srg.jar%23105!/data/.mcassetsroot' uses unexpected schema
[17:14:50] [Worker-Main-6/ERROR] [minecraft/TagLoader]: Couldn't load tag ctov:wares/cardboard_box as it is missing following references: wares:cardboard_box (from [Forge]CTOV-v3.4.5.jar)
[17:14:50] [Worker-Main-6/ERROR] [minecraft/TagLoader]: Couldn't load tag ctov:wares/sealed_delivery_agreement as it is missing following references: wares:sealed_delivery_agreement (from [Forge]CTOV-v3.4.5.jar)
[17:14:51] [Worker-Main-5/ERROR] [ne.mi.co.ForgeHooks/]: Couldn't parse element loot_tables:ctov:chests/village/village_forager
com.google.gson.JsonSyntaxException: Missing expand, expected to find a Boolean
        at net.minecraft.util.GsonHelper.m_13912_(GsonHelper.java:181) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.TagEntry$Serializer.m_7267_(TagEntry.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.TagEntry$Serializer.m_7267_(TagEntry.java:72) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_5921_(LootPoolSingletonContainer.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:86) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_7561_(LootPoolEntryContainer.java:74) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:102) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13836_(GsonHelper.java:471) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:192) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootPool$Serializer.deserialize(LootPool.java:189) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1290) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:179) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraft.util.GsonHelper.m_13808_(GsonHelper.java:463) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.util.GsonHelper.m_13845_(GsonHelper.java:481) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:294) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootTable$Serializer.deserialize(LootTable.java:291) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%2372!/:?] {}
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%2372!/:?] {}
        at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:871) ~[forge-1.20.1-47.3.5-universal.jar%23110!/:?] {re:classloading}
        at net.minecraftforge.common.ForgeHooks.lambda$getLootTableDeserializer$3(ForgeHooks.java:848) ~[forge-1.20.1-47.3.5-universal.jar%23110!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:45) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:56) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?] {}
        at net.minecraft.world.level.storage.loot.LootDataManager.m_278660_(LootDataManager.java:55) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}
[17:14:51] [main/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
[17:14:51] [main/INFO] [minecraft/AdvancementList]: Loaded 1271 advancements
[17:14:51] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.20.1
[17:14:51] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
[17:14:51] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
[17:14:51] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
[17:14:52] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:31168
[17:14:52] [Server thread/INFO] [minecraft/ServerConnectionListener]: Using epoll channel type
[17:14:52] [Server thread/WARN] [minecraft/DedicatedServer]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:14:52] [Server thread/WARN] [minecraft/DedicatedServer]: The server will make no attempt to authenticate usernames. Beware.
[17:14:52] [Server thread/WARN] [minecraft/DedicatedServer]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:14:52] [Server thread/WARN] [minecraft/DedicatedServer]: To change this, set "online-mode" to "true" in the server.properties file.
[17:14:52] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "Technoterra"
[17:14:53] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[17:14:56] [Worker-Main-5/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-1/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-1/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-2/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-2/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-1/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
[17:14:56] [Worker-Main-6/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 27%
[17:14:57] [Server thread/INFO] [minecraft/LoggerChunkProgressListener]: Time elapsed: 3492 ms
[17:14:57] [Server thread/INFO] [minecraft/DedicatedServer]: Done (5.196s)! For help, type "help"
[17:14:57] [Server thread/INFO] [minecraft/DedicatedServer]: Starting GS4 status listener
[17:14:57] [Server thread/INFO] [minecraft/GenericThread]: Thread Query Listener started
[17:14:57] [Query Listener #1/INFO] [minecraft/QueryThreadGs4]: Query running on 0.0.0.0:31168
[17:14:57] [Server thread/INFO] [ne.mi.se.pe.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
```

**Comment by tarkh** [comment]
Thank you for info, then closing )
