### ISSUE TITLE
failure to load world, illegalstateexception unbound value

### ISSUE THREAD

**Issue by rotwhip3** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#42]
trying to start new world, fails to load past 72%, issue in log as follows

[16:52:52] [Worker-Main-6/ERROR]: Failed to light chunk [1, 5]
java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:636) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	... 11 more
Caused by: java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/template_pool / ctov:pillager_outpost/beach/starts]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/template_pool] (Stable)]
	at net.minecraft.core.Holder$Reference.m_203334_(Holder.java:151) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.levelgen.structure.pools.JigsawPlacement.m_227238_(JigsawPlacement.java:270) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.levelgen.structure.structures.JigsawStructure.m_214086_(JigsawStructure.java:86) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.levelgen.structure.Structure.m_226596_(Structure.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223104_(ChunkGenerator.java:638) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223066_(ChunkGenerator.java:620) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_223164_(ChunkGenerator.java:573) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223360_(ChunkStatus.java:59) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23529!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]

version ctov-3.2.1.jar
repeatable on all new worlds, same issue, even on new install

**Comment by ChoiceTheorem** [comment]
Can you post the whole log?

**Comment by rotwhip3** [comment]
absolutley, please let me know if this works, the paste was too long to dirrect paste, and too large for a pastebin upload.

[2023-05-21-2.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/11555518/2023-05-21-2.log)
